Rollback the code with ck_resp_rollback set to false in pgxc_node_remote_prepare, as it will cause problems with "ROLLBACK TO" in "SAVEPOINT" as follows:
BEGIN;
	INSERT INTO savepoints VALUES (9);
	SAVEPOINT one;
		INSERT INTO savepoints VALUES (10);
	ROLLBACK TO SAVEPOINT one;
ERROR:  unexpected ROLLBACK from remote node
CONTEXT:  Error message received from nodes: datanode#1 datanode#2 coordinator#2
		INSERT INTO savepoints VALUES (11);
ERROR:  current transaction is aborted, commands ignored until end of transaction block
COMMIT;

Code change history is as follows:

SHA-1: 247ec4278507d9f9177c5eb4721b55200b9785a9

* http://tapd.oa.com/pgxz/bugtrace/bugs/view?bug_id=1010092131076775769

pgxc_node_remote_prepare：

	We can not set ck_resp_rollback to false here.
	If it is set to false, when the transaction is rolled back,
	the CN will not send Rollback command to DN in pgxc_node_remote_abort.
	in that case, the CN will roll back its own local transaction only.